


#define SPI_DATA SPIE.DATA
#define SPI_STATUS SPIE.STATUS
#define SPI_IF (SPIE.STATUS & SPI_IF_bm)
#define SPI_MAX_SET SPIE.CTRL = SPI_ENABLE_bm | SPI_MASTER_bm | SPI_MODE_0_gc | SPI_PRESCALER_DIV4_gc | 0x80
#define SPI_LCD_SET SPIE.CTRL = SPI_ENABLE_bm | SPI_MASTER_bm | SPI_MODE_0_gc | SPI_PRESCALER_DIV4_gc | 0x80
#define SPI_TOUCH_SET SPIE.CTRL = SPI_ENABLE_bm | SPI_MASTER_bm | SPI_MODE_0_gc | SPI_PRESCALER_DIV16_gc | 0x80
#define SPI_SD_SET SPIE.CTRL = SPI_ENABLE_bm | SPI_MASTER_bm | SPI_MODE_0_gc | SPI_PRESCALER_DIV4_gc | 0x80
#define SPI_LOW_SET SPIE.CTRL = SPI_ENABLE_bm | SPI_MASTER_bm | SPI_MODE_0_gc | SPI_PRESCALER_DIV128_gc

#define RAM_SPI_DATA SPIC.DATA
#define RAM_SPI_STATUS SPIC.STATUS
#define RAM_SPI_IF (SPIC.STATUS & SPI_IF_bm)
#define RAM_SPI_MAX_SET SPIC.CTRL = SPI_ENABLE_bm | SPI_MASTER_bm | SPI_MODE_0_gc | SPI_PRESCALER_DIV4_gc | 0x80

void mcu_set_32mhz(void);